version: "3"
networks:
  vector_server_default:
    external:
      name: vector_server_default
services:
  discord_bot:
#    image: ghcr.io/kamikazebr/qabot:main-vector_server
    env_file:
      - .env

