version: "3"
networks:
  vector_server_default:
    external: true
services:
  hivemind_api:
    restart: unless-stopped
    ports:
      - "3333:3333"
    networks:
      - vector_server_default
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/project/src
    command: [ "python","/project/src/api.py" ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3333/"]
