version: "3"
networks:
  vector_server_default:
    name: vector_server_default
services:
  hivemind_api:
    image: ghcr.io/kamikazebr/qabot:main-ml
    ports:
      - 3333:3333
    networks:
      - vector_server_default
    env_file:
      - .env