version: "3"
networks:
  vector_server_default:
    name: vector_server_default
services:
  hivemind_api:
    ports:
      - 3333:3333
    networks:
      - vector_server_default
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/project/
    command: [ "python","/project/src/api.py" ]
