version: "3"
networks:
  vector_server_default:
    external:
      name: vector_server_default
services:
  hivemind_api:
    ports:
      - "3333:3333"
    networks:
      - vector_server_default
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/project/src
    command: [ "python","/project/src/api.py" ]
