[tool.poetry]
name = "QABot"
version = "0.1.0"
description = ""
authors = [
    "Felipe Novaes Rocha <felipe.novaes.rocha@gmail.com>",
    "Tjitse van der Molen <tjitsevdmolen@gmail.com>",
]

[tool.poetry.group.dev.dependencies]
flake8 = "6.0.0"
black = "23.3.0"
isort = "5.12.0"


[tool.pdm]
[tool.pdm.dev-dependencies]
dev = []

[tool.pdm.build]
includes = []
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
authors = [
    {name = "Felipe Novaes Rocha", email = "felipe.novaes.rocha@gmail.com"},
    {name = "Tjitse van der Molen", email = "tjitsevdmolen@gmail.com"},
]
requires-python = ">=3.9,<3.12.1"
dependencies = [
    "openai<1.0.0,>=0.27.8",
    "python-dotenv<2.0.0,>=1.0.0",
    "jsonschema<5.0.0,>=4.17.3",
    "base58<3.0.0,>=2.1.1",
    "deeplake<4.0.0,>=3.6.1",
    "tiktoken<1.0.0,>=0.4.0",
    "fastapi<1.0.0,>=0.96.0",
    "langchain<1.0.0,>=0.0.193",
    "uvicorn[standard]<1.0.0,>=0.22.0",
    "python-jose[cryptography]<4.0.0,>=3.3.0",
    "siwe<3.0.0,>=2.2.0",
    "web3<7.0.0,>=6.4.0",
    "asgi-correlation-id<5.0.0,>=4.2.0",
    "pymongo<5.0.0,>=4.3.3",
    "backoff<3.0.0,>=2.2.1",
    "aiofiles>=23.2.1",
    "aio-pika>=9.3.0",
    "tc-messageBroker>=1.6.3",
    "faiss-cpu>=1.7.4",
]
name = "QABot"
version = "0.1.0"
description = ""

[project.group.dev.dependencies]
flake8 = "6.0.0"
black = "23.3.0"
isort = "5.12.0"
