[tool.poetry]
name = "VectorServer"
version = "0.1.0"
description = ""
authors = [
    "Felipe Novaes Rocha <felipe.novaes.rocha@gmail.com>",
    "Tjitse van der Molen <tjitsevdmolen@gmail.com>",
]

[tool.poetry.group.dev.dependencies]
flake8 = "6.0.0"
black = "23.3.0"
isort = "5.12.0"

[tool.pdm]
[tool.pdm.dev-dependencies]
dev = []

[tool.pdm.build]
includes = []
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
authors = [
    {name = "Felipe Novaes Rocha", email = "felipe.novaes.rocha@gmail.com"},
    {name = "Tjitse van der Molen", email = "tjitsevdmolen@gmail.com"},
]
requires-python = ">=3.9,<3.12.1"
dependencies = [
    "python-dotenv<2.0.0,>=1.0.0",
    "deeplake<4.0.0,>=3.6.1",
    "fastapi<1.0.0,>=0.96.0",
    "uvicorn[standard]<1.0.0,>=0.22.0",
    "asgi-correlation-id<5.0.0,>=4.2.0",
    "pymongo<5.0.0,>=4.3.3",
    "backoff<3.0.0,>=2.2.1",
    "tc-messagebroker<2.0.0,>=1.5.1",
    "openai<1.0.0,>=0.27.8",
    "celery[redis]>=5.3.4",
    "tiktoken<1.0.0,>=0.4.0",
    "langchain>=0.0.325",
]
name = "VectorServer"
version = "0.1.0"
description = ""

[project.group.dev.dependencies]
flake8 = "6.0.0"
black = "23.3.0"
isort = "5.12.0"
